// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApiTodo.Data;

#nullable disable

namespace MinimalApiTodo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260122080253_InitialFinalVersion")]
    partial class InitialFinalVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalApiTodo.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = false,
                            Title = "Обновить серверную ОС",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = true,
                            Title = "Исправить баг в корзине",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            Title = "Подготовить отчет за квартал",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = false,
                            Title = "Протестировать API авторизации",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = true,
                            Title = "Создать макет главной страницы",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            IsCompleted = false,
                            Title = "Настроить CI/CD пайплайны",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            IsCompleted = false,
                            Title = "Провести собеседование с кандидатом",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            IsCompleted = true,
                            Title = "Позвонить ключевому клиенту",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            IsCompleted = false,
                            Title = "Ответить на тикеты в Jira",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            IsCompleted = false,
                            Title = "Оптимизировать SQL запросы",
                            UserId = 10
                        });
                });

            modelBuilder.Entity("MinimalApiTodo.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivan@example.com",
                            PasswordHash = "$2a$11$UD5xr2eiHPmn5OMpAPQ2XOfJ10ZJvnH9LAAqbXRqSaWra74dfK/IO",
                            Role = 1,
                            UserName = "ivan_admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria@example.com",
                            PasswordHash = "$2a$11$UD5xr2eiHPmn5OMpAPQ2XOfJ10ZJvnH9LAAqbXRqSaWra74dfK/IO",
                            Role = 1,
                            UserName = "maria_dev"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alex@example.com",
                            PasswordHash = "$2a$11$UD5xr2eiHPmn5OMpAPQ2XOfJ10ZJvnH9LAAqbXRqSaWra74dfK/IO",
                            Role = 1,
                            UserName = "alex_manager"
                        },
                        new
                        {
                            Id = 4,
                            Email = "dmitry@example.com",
                            PasswordHash = "$2a$11$UD5xr2eiHPmn5OMpAPQ2XOfJ10ZJvnH9LAAqbXRqSaWra74dfK/IO",
                            Role = 1,
                            UserName = "dmitry_test"
                        },
                        new
                        {
                            Id = 5,
                            Email = "elena@example.com",
                            PasswordHash = "$2a$11$UD5xr2eiHPmn5OMpAPQ2XOfJ10ZJvnH9LAAqbXRqSaWra74dfK/IO",
                            Role = 1,
                            UserName = "elena_design"
                        },
                        new
                        {
                            Id = 6,
                            Email = "sergey@example.com",
                            PasswordHash = "$2a$11$UD5xr2eiHPmn5OMpAPQ2XOfJ10ZJvnH9LAAqbXRqSaWra74dfK/IO",
                            Role = 0,
                            UserName = "sergey_tech"
                        },
                        new
                        {
                            Id = 7,
                            Email = "olga@example.com",
                            PasswordHash = "$2a$11$UD5xr2eiHPmn5OMpAPQ2XOfJ10ZJvnH9LAAqbXRqSaWra74dfK/IO",
                            Role = 1,
                            UserName = "olga_hr"
                        },
                        new
                        {
                            Id = 8,
                            Email = "igor@example.com",
                            PasswordHash = "$2a$11$UD5xr2eiHPmn5OMpAPQ2XOfJ10ZJvnH9LAAqbXRqSaWra74dfK/IO",
                            Role = 1,
                            UserName = "igor_sales"
                        },
                        new
                        {
                            Id = 9,
                            Email = "anna@example.com",
                            PasswordHash = "$2a$11$UD5xr2eiHPmn5OMpAPQ2XOfJ10ZJvnH9LAAqbXRqSaWra74dfK/IO",
                            Role = 1,
                            UserName = "anna_support"
                        },
                        new
                        {
                            Id = 10,
                            Email = "pavel@example.com",
                            PasswordHash = "$2a$11$UD5xr2eiHPmn5OMpAPQ2XOfJ10ZJvnH9LAAqbXRqSaWra74dfK/IO",
                            Role = 1,
                            UserName = "pavel_backend"
                        });
                });

            modelBuilder.Entity("MinimalApiTodo.TodoItem", b =>
                {
                    b.HasOne("MinimalApiTodo.User", "User")
                        .WithMany("TodoItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MinimalApiTodo.User", b =>
                {
                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
